language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-16
    - android-28
    - build-tools-28.0.3

script: ./gradlew clean build test